apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: helloworld
  ports:
    - name: http
      nodePort: 31704
      port: 3333
      protocol: TCP
      targetPort: 3333